---
apiVersion: getambassador.io/v2
kind: RateLimit
metadata:
  name: token-name-rate-limit
spec:
  domain: ambassador
  limits:
  - name: token-name-per-minute
    action: Enforce
    pattern:
    - headerkey: ""                   # Each unique header value of "x-token-name" is tracked individually
    rate: 3
    unit: "minute"